media_folder: "src/assets/images/uploads"
public_folder: "assets/images/uploads"
backend:
  name: git-gateway
  branch: main

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/site/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Post Body", name: "body", widget: "markdown" }
